version: 0.2

env:
  parameter-store:
    CUSTOM_DOMAIN_NAME: 'dev.CUSTOM_DOMAIN_NAME'
    CERTIFICATE_NAME: 'dev.CERTIFICATE_NAME'

phases:
  install:
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - sls deploy
