service: spike-serverless-framework # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    TEST_DYNAMODB_TABLE: test-${self:service}-${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # dbPath: '<mypath>/'
      # noStart: true
  customDomain:
    domainName: ${self:provider.stage}-spike-serverless.${env:CUSTOM_DOMAIN_NAME}
    certificateName: ${env:CERTIFICATE_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: /hello
          method: GET
  imageScraper:
    handler: src/functions/handler.imageScraper
    events:
      - http:
          path: /image-scraper
          method: POST
  simplePut:
    handler: src/functions/handler.simplePut
    events:
      - http:
          path: /simple-put
          method: POST

resources:
  Resources:
    SpikeServerlessFrameworkTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SpikeServerlessFrameworkTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEST_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: message
            AttributeType: S
        KeySchema:
          - AttributeName: message
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
