service: spike-serverless-framework # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/*-${self:provider.stage}'
    - Effect: Allow
      Action:
        - 'sqs:SendMessage'
        - 'sqs:GetQueueUrl'
        - 'sqs:CreateQueue'
      Resource: 'arn:aws:sqs:${self:provider.region}:*:*-${self:provider.stage}'
  environment:
    SQS_BASE_URL: ${self:custom.configFile.${self:provider.stage}.SQS_BASE_URL}
    TEST_QUEUE_NAME: ${self:service}-${self:provider.stage}
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    TEST_DYNAMODB_TABLE: test-${self:service}-${self:provider.stage}
    IMAGES_DYNAMODB_TABLE: images-${self:service}-${self:provider.stage}
    PIXABAY_API_KEY: ${self:custom.configFile.${self:provider.stage}.PIXABAY_API_KEY}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # dbPath: '<mypath>/'
      # noStart: true
  customDomain:
    domainName: ${self:provider.stage}-spike-serverless.${env:CUSTOM_DOMAIN_NAME}
    certificateName: ${env:CERTIFICATE_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
  configFile:
    dev: ${file(./config/dev.yml)}

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: /hello
          method: GET
  imageScraper:
    handler: src/functions/handler.imageScraper
    events:
      - http:
          path: /image-scraper
          method: POST
  simplePut:
    handler: src/functions/handler.simplePut
    events:
      - http:
          path: /simple-put
          method: POST
  searchPixabay:
    handler: src/functions/handler.searchPixabay
    events:
      - http:
          path: /search-pixabay
          method: GET
  putToSQS:
    handler: src/functions/handler.putToSQS
    events:
      - http:
          path: /put-to-sqs
          method: POST
  sqsTriggered:
    handler: src/functions/handler.sqsTriggered
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TestQueue
              - Arn

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.TEST_QUEUE_NAME}
    SpikeServerlessFrameworkTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SpikeServerlessFrameworkTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEST_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: message
            AttributeType: S
        KeySchema:
          - AttributeName: message
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SpikeServerlessFrameworkImagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.IMAGES_DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: query
            AttributeType: S
        KeySchema:
          - AttributeName: query
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
