service: spike-serverless-framework # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:provider.stage}-spike-serverless.${env:CUSTOM_DOMAIN_NAME}
    certificateName: ${env:CERTIFICATE_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'

functions:
  hello:
    handler: src/functions/handler.hello
    events:
      - http:
          path: /hello
          method: GET
  imageScraper:
    handler: src/functions/handler.imageScraper
    events:
      - http:
          path: /image-scraper
          method: GET
